export const InventoryFiltersActionTypes = {
    TOGGLE_FIXED:'TOGGLE_FIXED',
    SET_FIELD_VALUE:'SET_FILTERS_FIELD_VALUE',
    APPEND_OPTION:'APPEND_OPTION',
    REMOVE_OPTION:'REMOVE_OPTION',
    RESET_FILTERS:"RESET_FILTERS"
}