export default {
    SET_FIELD_VALUE: "SET_EDIT_LISTING_FIELD_VALUE",
    SET_INITIAL_VALUES:"SET_INITIAL_VALUES",
    ADD_IMAGE:"EDIT_LISTING_ADD_IMAGE",
    SET_FILE_LIST:"EDIT_LISTING_SET_FILE_LIST",
    EDITTING_SUCCESS:"EDITTING_SUCCESS"
}