const ListingsActionTypes = {
    FETCH_LISTINGS_START:'FETCH_LISTINGS_START',
    FETCH_LISTINGS_SUCCESS:'FETCH_LISTINGS_SUCCESS',
    FETCH_LISTINGS_FAILURE:'FETCH_LISTINGS_FAILURE',
    ADD_LISTING:'ADD_LISTING',
    REMOVE_LISTING:"REMOVE_LISTING",
    EDIT_LISTING:'EDIT_LISTING'
}
export default ListingsActionTypes