const ListingsActionTypes = {
    FETCH_LISTINGS_START:'FETCH_LISTINGS_START',
    FETCH_LISTINGS_SUCCESS:'FETCH_LISTINGS_SUCCESS',
    FETCH_LISTINGS_FAILURE:'FETCH_LISTINGS_FAILURE',
    ADD_LISTING:'ADD_LISTING',
    REMOVE_LISTING:"REMOVE_LISTING",
    EDIT_LISTING_START:'EDIT_LISTING_START',
    EDIT_LISTING_SUCCESS:'EDIT_LISTING_SUCCESS',
    EDIT_LISTING_FAILURE:'EDIT_LISTING_FAILURE',
    ADD_LISTING_START:"ADD_LISTING_START",
    ADD_LISTING_SUCCESS:"ADD_LISTING_SUCCESS",
    ADD_LISTING_FAILURE: "ADD_LISTING_FAILURE",
    TOGGLE_PARKING:'TOGGLE_PARKING',
    TOGGLE_COMPARE:'TOGGLE_COMPARE',
    FETCH_OWN_LISTING_START:'FETCH_OWN_LISTING_START',
    FETCH_OWN_LISTING_SUCCESS:'FETCH_OWN_LISTING_SUCCESS',
    FETCH_OWN_LISTINGS_FAILURE:'FETCH_OWN_LISTING_FAILURE',


}
export default ListingsActionTypes